Check for python

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -139,7 +139,7 @@ function has_travis_with_proselint {
 
 
 
-# Does the user's repo have a .travis.yml with proselint?
+# Does the user's repo have a .travis.yml that checks dead links?
 # @param $1: username
 # @param $2: reponame
 # @return 1 if pass, 0 if fails
@@ -166,6 +166,33 @@ function has_travis_find_find_dead_links {
   fi
 }
 
+
+# Does the user's repo have a .travis.yml that runs a python script?
+# @param $1: username
+# @param $2: reponame
+# @return 1 if pass, 0 if fails
+function has_travis_with_python {
+  username=$1
+  reponame=$2
+
+  if [[ `has_travis $username $reponame` != 1 ]] ;
+  then
+    echo "0"
+    return
+  fi 
+  wget -q https://raw.githubusercontent.com/$username/$reponame/master/.travis.yml -O tmp.txt
+
+  n_lines=`egrep "python" tmp.txt | wc --lines | cut -f 1 -d " "`
+
+  rm tmp.txt
+
+  if [[ $n_lines == 0 ]] ;
+  then
+    echo "0"
+  else
+    echo "1"
+  fi
+}
 
 
 # Get the number of points, for a known user and repo
@@ -200,6 +227,9 @@ function get_points {
   # 7. Have a .travis.yml that checks dead links
   point_seven=`has_travis_find_find_dead_links $username $reponame`
 
+  # 8. Have a .travis.yml that runs a Python script
+  point_eight=`has_travis_with_python $username $reponame`
+
   # Show report
   echo >&2 "Report"
   echo >&2 "1: correct_cpp_scoreboard: "$point_one
@@ -209,14 +239,55 @@ function get_points {
   echo >&2 "5: has README with presentation: "$point_five
   echo >&2 "6: has .travis.yml with proselint: "$point_six
   echo >&2 "7: has .travis.yml that checks dead links: "$point_seven
+  echo >&2 "8: has .travis.yml that runs a Python script: "$point_eight
 
 
-  n_points=$((point_one + point_two + point_three + point_four + point_five + point_six + point_seven))
+  n_points=$((point_one + point_two + point_three + point_four + point_five + point_six + point_seven + point_eight))
   echo $n_points
 }
 
+# Get the username from file
+# @param $1: filename
+# @return the username
+function get_username {
+
+  filename=$1
+
+  # No text file results in the grade 1
+  if [[ ! -f $filename ]] ; 
+  then
+    echo "[unknown]"
+    return
+  fi
+
+  # Username is in the first line, after a whitespace
+  username=`cat $filename | head -n 1 | tail -n 1 | cut -d " " -f 2`
+  echo $username
+}
+
+# Get the reponame from file
+# @param $1: filename
+# @return the username
+function get_reponame {
+
+  filename=$1
+
+  # No text file results in the grade 1
+  if [[ ! -f $filename ]] ; 
+  then
+    echo "[unknown]"
+    return
+  fi
+
+  # Username is in the first line, after a whitespace
+  reponame=`cat $filename | head -n 2 | tail -n 1 | cut -d " " -f 2`
+  echo $reponame
+}
+
+
 # Get the grade, after extracing user and repo from file
 # @param $1: filename
+# @return the grade as a number from 1 to 10
 function get_grade {
 
   filename=$1
