Check for proselint

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -21,6 +21,23 @@ function pass_build {
   echo $pass
 }
 
+# Does the user's repo has a .travis.yml?
+# @param $1: username
+# @param $2: reponame
+# @return 1 if pass, 0 if fails
+function has_travis {
+  username=$1
+  reponame=$2
+  wget -q https://github.com/$username/$reponame/blob/master/.travis.yml -O /dev/null
+  exit_code=$?
+  if [[ $exit_code == 0 ]] ;
+  then
+    echo "1"
+  else
+    echo "0"
+  fi
+}
+
 # Does the user's repo has a README.md?
 # @param $1: username
 # @param $2: reponame
@@ -91,6 +108,34 @@ function has_readme_with_presentation {
     echo "1"
   fi
 }
+
+# Does the user's repo have a .travis.yml with proselint?
+# @param $1: username
+# @param $2: reponame
+# @return 1 if pass, 0 if fails
+function has_travis_with_proselint {
+  username=$1
+  reponame=$2
+
+  if [[ `has_travis $username $reponame` != 1 ]] ;
+  then
+    echo "0"
+    return
+  fi 
+  wget -q https://raw.githubusercontent.com/$username/$reponame/master/.travis.yml -O tmp.txt
+
+  n_lines=`egrep "proselint" tmp.txt | wc --lines | cut -f 1 -d " "`
+
+  rm tmp.txt
+
+  if [[ $n_lines == 0 ]] ;
+  then
+    echo "0"
+  else
+    echo "1"
+  fi
+}
+
 
 # Get the number of points, for a known user and repo
 # @param $1: username
