Grade README

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -21,20 +21,49 @@ function pass_build {
   echo $pass
 }
 
+# Does the user's repo has a README.md?
+# @param $1: username
+# @param $2: reponame
+# @return 1 if pass, 0 if fails
+function has_readme {
+  username=$1
+  reponame=$2
+  wget -q https://github.com/$username/$reponame/blob/master/README.md -O /dev/null
+  exit_code=$?
+  if [[ $exit_code == 0 ]] ;
+  then
+    echo "1"
+  else
+    echo "0"
+  fi
+}
+
 # Get the number of points, for a known user and repo
 # @param $1: username
 # @param $2: reponame
 # @return 1 if pass, 0 if fails
 function get_points {
 
+  username=$1
+  reponame=$1
+
   # Start grading
+
+  # 1. Do correct_cpp_scoreboard
   point_one=`pass_build $username correct_cpp_scoreboard`
+
+  # 2. Do correct_cpp_hello
   point_two=`pass_build $username correct_cpp_hello`
+
+  # 3. Have a README.md at repo
+  point_three=`has_readme $username $reponame`
+  
 
   # Show report
   echo >&2 "Report"
   echo >&2 "1: correct_cpp_scoreboard: "$point_one
   echo >&2 "2: correct_cpp_hello: "$point_two
+
 
   n_points=$((point_one + point_two))
   echo $n_points
